name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 4.2.2

homepage: https://github.com/ketanchoyal/mapbox_search

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0
  json_annotation: ^4.4.0
  uuid: ^4.0.0
  color: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.6
  meta: ^1.10.0
  http_multi_server: ^3.2.1
  json_serializable: ^6.3.0
  build_runner: ^2.1.0
