name: mapbox_search
description: A Flutter package for place search using MapBox Api and for Static map image
version: 3.1.1

homepage: https://github.com/ketanchoyal/mapbox_search

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  meta: ^1.3.0
  http_multi_server: ^3.0.0
